//
//  ListWorker.swift
//  Weather
//
//  Created by chawapon.kiatpravee on 1/8/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol ListWorkerProtocol {
    func request5DaysForecast(cityId: Int, completion: @escaping ForecastResponseHandler)
    func requestWeatherImage(iconCode: String, completion: @escaping WeatherIconResponseHandler)
}

class ListWorker: ListWorkerProtocol {
    var manager: ApiManager?
    
    init(manager: ApiManager? = nil) {
        self.manager = manager ?? ApiManager()
    }
    
    func request5DaysForecast(cityId: Int, completion: @escaping ForecastResponseHandler) {
        manager?.get5DaysForecast(cityId: cityId, completion: completion)
    }
    
    func requestWeatherImage(iconCode: String, completion: @escaping WeatherIconResponseHandler) {
        manager?.getWeatherIcon(iconCode: iconCode, completion: completion)
    }
}
