//
//  HomeRouter.swift
//  Weather
//
//  Created by chawapon.kiatpravee on 1/8/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeRoutingLogic {
    func routeToAlert(message: String)
    func routeTo5DaysForecast(cityId: Int, tempUnit: TemperatureUnit)
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    // MARK: Routing
    
    func routeToAlert(message: String) {
        showAlert(message: message, viewController: viewController)
    }
    
    func routeTo5DaysForecast(cityId: Int, tempUnit: TemperatureUnit) {
        guard let destinationVC = UIStoryboard(name: "Weather", bundle: nil).instantiateViewController(withIdentifier: "ListViewController") as? ListViewController else {
            return
        }
        destinationVC.router?.dataStore?.cityId = cityId
        destinationVC.router?.dataStore?.tempUnit = tempUnit
        viewController?.present(destinationVC, animated: true)
    }
}
